"""empty message

Revision ID: 46e828c129d2
Revises: 
Create Date: 2018-09-07 16:06:15.004338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46e828c129d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('newtag', sa.String(length=200), nullable=False))
    op.drop_column('movie', 'tags')
    op.add_column('tag', sa.Column('tagName', sa.String(length=200), nullable=False))
    op.drop_column('tag', 'tagname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tagname', mysql.VARCHAR(charset='utf8', length=100), nullable=True))
    op.drop_column('tag', 'tagName')
    op.add_column('movie', sa.Column('tags', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('movie', 'newtag')
    # ### end Alembic commands ###
