"""empty message

Revision ID: 76b4ab66a9ad
Revises: 
Create Date: 2018-09-03 20:55:25.937696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76b4ab66a9ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
